#version de sintaxis
version: "3.9"

#definir servicios
services:
  proyectos-backend:
    container_name: proyectos-backend
    image: proyectos-backend:v2
    build:
      context: .
    ports:
      - 4000:4000
    networks:
      - proyectos-app

networks:
  proyectos-app: